#!/bin/sh

_DO_META_ADDR=http://169.254.169.254/metadata/v1

check() {
    [ -n "$(fetch_url "$_DO_META_ADDR/id")" ]
}

load() {
    NAME="$(fetch_url "$_DO_META_ADDR/hostname" 2>/dev/null)"
    DATA="$(fetch_url "$_DO_META_ADDR/user-data" 2>/dev/null)"
    KEYS="$(fetch_url "$_DO_META_ADDR/public-keys" 2>/dev/null)"
}
